on:
  push:
    branches:
    - master
  schedule:
  - cron: "0 * * * *"

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: github and support
      env:
        WORKFLOW_FILE_PATH: ${{ github.workflow }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: |
